package TestLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseConstraintsAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class ConstraintsAspectDescriptor extends BaseConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }

  @Override
  public ConstraintsDescriptor getConstraints(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return new AssertStatement_Constraints();
      case 1:
        return new ExecuteSigleTestCase_Constraints();
      case 2:
        return new TestCase_Constraints();
      default:
    }
    return new BaseConstraintsDescriptor(concept);
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xd841915f93084767L, 0x8fc4b848d3400fafL, 0x276ac52d000d8a7cL), MetaIdFactory.conceptId(0xd841915f93084767L, 0x8fc4b848d3400fafL, 0xaf9586bd50c0b92L), MetaIdFactory.conceptId(0xd841915f93084767L, 0x8fc4b848d3400fafL, 0x276ac52d000d0102L)).seal();
}
