package SoseL21.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ElseStatement_Constraints extends BaseConstraintsDescriptor {
  public ElseStatement_Constraints() {
    super(CONCEPTS.ElseStatement$KW);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ElseStatement$KW = MetaAdapterFactory.getConcept(0x675036cf295d4c04L, 0xa4188a54769c9d5cL, 0x420569f62aafe104L, "SoseL21.structure.ElseStatement");
  }
}
