package SoseL21.sandbox.interpreter.plugin;

/*Generated by MPS */

import jetbrains.mps.smodel.structure.Extension;
import com.mbeddr.mpsutil.interpreter.rt.IInterpreter;
import com.mbeddr.mpsutil.interpreter.rt.CachedInterpreterFinder;

public class ExprInterpreter_extension extends Extension.Default<IInterpreter> {
  public ExprInterpreter_extension() {
    super("com.mbeddr.mpsutil.interpreter.InterpreterExtensionPoint");
  }

  public void activate() {
    CachedInterpreterFinder.getInstance().flushCache();
  }
  public void deactivate() {
    CachedInterpreterFinder.getInstance().flushCache();
  }

  public IInterpreter get() {
    return new InterpreterExprInterpreter();
  }
}
