package TestLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int AssertStatement = 0;
  public static final int TestCase = 1;
  public static final int TestSuite = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xd841915f93084767L, 0x8fc4b848d3400fafL);
    builder.put(0x276ac52d000d8a7cL, AssertStatement);
    builder.put(0x276ac52d000d0102L, TestCase);
    builder.put(0x276ac52d000d00ffL, TestSuite);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
