package SoseL21.sandbox;

/*Generated by MPS */


public class wk1 {
  public static void main(String[] args) {
    int a = 1;
    boolean ceva = true;
    func1();
    tibi(8);
    tibi(a);
    func2(true, 7);
  }

  public static int tibi(int param) {
    int b = 3;
    boolean c = true;
    return 1;
  }
  public static void func1() {
    int var1 = 1;
    var1 = 2;
    return;
  }
  public static void func2(boolean a, int b) {
    return;
  }
}
