package SoseL21.sandbox;

/*Generated by MPS */


public class wk1 {
  public static void main(String[] args) {
    int a = 1 - 9 * 7;
    boolean altceva = false;
  }

  public void tibi(int par1, boolean par2) {
    return;
  }
}
