package SoseL21.sandbox;

/*Generated by MPS */


public class wk1 {
  public static void main(String[] args) {
    int a = 1;
    boolean ceva = true;
    String f = "test";
    String bla = "interesant";
    func1();
    tibi(8);
    tibi(a);
    func2(true, 7);
  }

  public static int tibi(int param) {
    int b = 3;
    boolean c = true;
    return 1;
  }
  public static void func1() {
    int var1 = 1;
    var1 = 2;
    return;
  }
  public static boolean func2(boolean bla, int blabla) {
    while (bla) {
      if (blabla > 1) {
        blabla = 2;
      }
      int l = 2;
    }
    if (blabla > 1) {
      if (bla) {
        bla = true;
      }
    }
    return true;
  }
}
